# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thank you for opening an issue. Make sure that you star the project as it encourages our contributors to work hard :)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines and support our work by starring us :star:

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! Thanks a lot! Did you star the repo yet? 
